const PROJECTS_DATA = {
    "maison-dagde": {
        "title": "La Maison d'Agde",
        "category": "Particulier",
        "location": "Agde",
        "description": "Une rénovation contemporaine alliant épure et confort dans le centre historique.",
        "folder": "assets/images/realisations/particuliers/01-maison-dagde",
        "hero": "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "images": [
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-4.webp"
        ]
    },
    "maison-cersoise": {
        "title": "Maison Cersoise",
        "category": "Particulier",
        "location": "Cers",
        "description": "L'élégance du design italien au cœur d'une villa méditerranéenne.",
        "folder": "assets/images/realisations/particuliers/02-maison-cersoise",
        "hero": "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
        "images": [
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-3.webp"
        ]
    },
    "maison-coloree": {
        "title": "La Maison Colorée",
        "category": "Particulier",
        "location": "Béziers",
        "description": "Un jeu audacieux de textures et de couleurs pour un intérieur vibrant.",
        "folder": "assets/images/realisations/particuliers/03-maison-coloree",
        "hero": "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "thumbnail": "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
        "images": [
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "appartement-nimes": {
        "title": "Appartement Nîmes",
        "category": "Particulier",
        "location": "Nîmes",
        "description": "Minimalisme et lumière pour cet appartement de ville aux lignes pures.",
        "folder": "assets/images/realisations/particuliers/04-appartement-nimes",
        "hero": "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
        "thumbnail": "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "images": [
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "lago-cap-dagde": {
        "title": "Lago Welcome Cap d'Agde",
        "category": "Particulier",
        "location": "Cap d'Agde",
        "description": "L'univers suspendu de Lago pour une expérience de vie unique face à la mer.",
        "folder": "assets/images/realisations/particuliers/05-lago-cap-dagde",
        "hero": "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "thumbnail": "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
        "images": [
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "maison-st-clement": {
        "title": "Maison St Clément",
        "category": "Particulier",
        "location": "St Clément de Rivière",
        "description": "Aménagement et décoration d'une maison de caractère pour un intérieur élégant et intemporel.",
        "folder": "assets/images/realisations/particuliers/06-maison-st-clement",
        "hero": "maison-st-clement-mobilier-design-beziers-1.webp",
        "thumbnail": "maison-st-clement-mobilier-design-beziers-6.webp",
        "images": [
            "maison-st-clement-mobilier-design-beziers-1.webp",
            "maison-st-clement-mobilier-design-beziers-2.webp",
            "maison-st-clement-mobilier-design-beziers-3.webp",
            "maison-st-clement-mobilier-design-beziers-4.webp",
            "maison-st-clement-mobilier-design-beziers-5.webp",
            "maison-st-clement-mobilier-design-beziers-6.webp",
            "maison-st-clement-mobilier-design-beziers-7.webp",
            "maison-st-clement-mobilier-design-beziers-8.webp",
            "maison-st-clement-mobilier-design-beziers-9.webp",
            "maison-st-clement-mobilier-design-beziers-10.webp"
        ]
    },
    "technilum": {
        "title": "Technilum",
        "category": "Professionnel",
        "location": "Maureilhan",
        "description": "Aménagement d'espaces de travail innovants alliant ergonomie et esthétique industrielle.",
        "folder": "assets/images/realisations/professionnels/01-technilum",
        "hero": "technilum-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://www.technilum.com/",
        "images": [
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-10.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-11.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-8.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-9.webp"
        ]
    },
    "cassina-villa-guy": {
        "title": "Cassina à la Villa Guy",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Une rencontre prestigieuse entre le mobilier Cassina et le cadre historique de la Villa Guy.",
        "folder": "assets/images/realisations/professionnels/02-cassina-villa-guy",
        "hero": "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
        "thumbnail": "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "images": [
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-10.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-11.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-12.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-8.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-9.webp"
        ]
    },
    "mediatheque-beziers": {
        "title": "Médiathèque Béziers",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Un espace public repensé pour le confort, la lecture et l'échange culturel.",
        "folder": "assets/images/realisations/professionnels/03-mediatheque-beziers",
        "hero": "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
        "thumbnail": "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
        "website": "http://www.mediatheque-beziers-agglo.org",
        "images": [
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-4.webp"
        ]
    },
    "projet-photo": {
        "title": "Projet Photo",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Mise en scène artistique de mobiliers iconiques dans un cadre architectural singulier.",
        "folder": "assets/images/realisations/professionnels/04-projet-photo",
        "hero": "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "images": [
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-7.webp"
        ]
    },
    "hotel-la-prison": {
        "title": "Hôtel La Prison",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Une métamorphose audacieuse où l'histoire rencontre le luxe contemporain.",
        "folder": "assets/images/realisations/professionnels/05-hotel-la-prison",
        "hero": "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "thumbnail": "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
        "website": "https://www.hotellaprison.com/",
        "images": [
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "hotel-particulier": {
        "title": "Hôtel Particulier",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Restauration d'un lieu d'exception avec une sélection de pièces de design intemporelles.",
        "folder": "assets/images/realisations/professionnels/06-hotel-particulier",
        "hero": "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://hotelparticulierbeziers.com",
        "images": [
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "appartement-lago-villa-guy": {
        "title": "Appartement Lago Villa Guy",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "L'élégance du mobilier italien dans un écrin biterrois historique.",
        "folder": "assets/images/realisations/professionnels/07-appartement-lago-villa-guy",
        "hero": "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://www.lavillaguy.com",
        "images": [
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "souki-lodge": {
        "title": "Souki Lodge",
        "category": "Professionnel",
        "location": "Cabrières",
        "description": "Une immersion sensorielle au design organique, suspendue entre ciel et terre.",
        "folder": "assets/images/realisations/professionnels/08-souki-lodge",
        "hero": "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
        "website": "https://www.soukilodgesandspa.com/",
        "images": [
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-8.webp"
        ]
    },
    "grand-hotel-du-golfe": {
        "title": "Grand Hôtel du Golfe",
        "category": "Professionnel",
        "location": "Argelès-sur-Mer",
        "description": "Mobilier contemporain et scénographie d'exception pour cet établissement historique de la Côte Vermeille, où le design dialogue avec la mer.",
        "folder": "assets/images/realisations/professionnels/09-grand-hotel-du-golfe",
        "hero": "grand-hotel-du-golfe-mobilier-design-beziers-4.webp",
        "thumbnail": "grand-hotel-du-golfe-mobilier-design-beziers-2.webp",
        "website": "https://www.grandhoteldugolfe.com/",
        "images": [
            "grand-hotel-du-golfe-mobilier-design-beziers-1.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-2.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-3.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-4.webp"
        ]
    },
    "arlett-cafe": {
        "title": "Arlett Café",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Arlett Café.",
        "folder": "assets/images/realisations/professionnels/10-arlett-cafe",
        "hero": "arlett-cafe-3.webp",
        "thumbnail": "arlett-cafe-3.webp",
        "images": [
            "arlett-cafe-1.webp",
            "arlett-cafe-10.webp",
            "arlett-cafe-11.webp",
            "arlett-cafe-12.webp",
            "arlett-cafe-13.webp",
            "arlett-cafe-14.webp",
            "arlett-cafe-15.webp",
            "arlett-cafe-16.webp",
            "arlett-cafe-17.webp",
            "arlett-cafe-18.webp",
            "arlett-cafe-19.webp",
            "arlett-cafe-2.webp",
            "arlett-cafe-20.webp",
            "arlett-cafe-21.webp",
            "arlett-cafe-22.webp",
            "arlett-cafe-23.webp",
            "arlett-cafe-24.webp",
            "arlett-cafe-3.webp",
            "arlett-cafe-4.webp",
            "arlett-cafe-5.webp",
            "arlett-cafe-6.webp",
            "arlett-cafe-7.webp",
            "arlett-cafe-8.webp",
            "arlett-cafe-9.webp"
        ]
    },
    "bureaux": {
        "title": "Bureaux",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Bureaux.",
        "folder": "assets/images/realisations/professionnels/11-bureaux",
        "hero": "bureaux-9.webp",
        "thumbnail": "bureaux-1.webp",
        "images": [
            "bureaux-1.webp",
            "bureaux-10.webp",
            "bureaux-11.webp",
            "bureaux-12.webp",
            "bureaux-13.webp",
            "bureaux-14.webp",
            "bureaux-15.webp",
            "bureaux-16.webp",
            "bureaux-17.webp",
            "bureaux-18.webp",
            "bureaux-19.webp",
            "bureaux-2.webp",
            "bureaux-20.webp",
            "bureaux-21.webp",
            "bureaux-22.webp",
            "bureaux-23.webp",
            "bureaux-24.webp",
            "bureaux-25.webp",
            "bureaux-26.webp",
            "bureaux-27.webp",
            "bureaux-28.webp",
            "bureaux-29.webp",
            "bureaux-3.webp",
            "bureaux-4.webp",
            "bureaux-5.webp",
            "bureaux-6.webp",
            "bureaux-7.webp",
            "bureaux-8.webp",
            "bureaux-9.webp"
        ]
    },
    "halles": {
        "title": "Les Halles",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Les Halles.",
        "folder": "assets/images/realisations/professionnels/12-halles",
        "hero": "halles-6.webp",
        "thumbnail": "halles-12.webp",
        "images": [
            "halles-1.webp",
            "halles-10.webp",
            "halles-11.webp",
            "halles-12.webp",
            "halles-13.webp",
            "halles-14.webp",
            "halles-15.webp",
            "halles-16.webp",
            "halles-17.webp",
            "halles-18.webp",
            "halles-19.webp",
            "halles-2.webp",
            "halles-20.webp",
            "halles-3.webp",
            "halles-4.webp",
            "halles-5.webp",
            "halles-6.webp",
            "halles-7.webp",
            "halles-8.webp",
            "halles-9.webp"
        ]
    },
    "imprimerie-combes-hund": {
        "title": "Imprimerie Combes Hund",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Imprimerie Combes Hund.",
        "folder": "assets/images/realisations/professionnels/13-imprimerie-combes-hund",
        "hero": "imprimerie-combes-hund-1.webp",
        "thumbnail": "imprimerie-combes-hund-3.webp",
        "images": [
            "imprimerie-combes-hund-1.webp",
            "imprimerie-combes-hund-2.webp",
            "imprimerie-combes-hund-3.webp",
            "imprimerie-combes-hund-4.webp",
            "imprimerie-combes-hund-5.webp",
            "imprimerie-combes-hund-6.webp"
        ]
    },
    "le-bistrot-cersois": {
        "title": "Le Bistrot Cersois",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Le Bistrot Cersois.",
        "folder": "assets/images/realisations/professionnels/14-le-bistrot-cersois",
        "hero": "le-bistrot-cersois-20.webp",
        "thumbnail": "le-bistrot-cersois-19.webp",
        "images": [
            "le-bistrot-cersois-1.webp",
            "le-bistrot-cersois-10.webp",
            "le-bistrot-cersois-11.webp",
            "le-bistrot-cersois-14.webp",
            "le-bistrot-cersois-15.webp",
            "le-bistrot-cersois-16.webp",
            "le-bistrot-cersois-17.webp",
            "le-bistrot-cersois-18.webp",
            "le-bistrot-cersois-19.webp",
            "le-bistrot-cersois-2.webp",
            "le-bistrot-cersois-20.webp",
            "le-bistrot-cersois-4.webp",
            "le-bistrot-cersois-5.webp",
            "le-bistrot-cersois-8.webp",
            "le-bistrot-cersois-9.webp"
        ]
    },
    "le-chameau-ivre": {
        "title": "Le Chameau Ivre",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Le Chameau Ivre.",
        "folder": "assets/images/realisations/professionnels/15-le-chameau-ivre",
        "hero": "le-chameau-ivre-11.webp",
        "thumbnail": "le-chameau-ivre-26.webp",
        "images": [
            "le-chameau-ivre-1.webp",
            "le-chameau-ivre-10.webp",
            "le-chameau-ivre-11.webp",
            "le-chameau-ivre-12.webp",
            "le-chameau-ivre-13.webp",
            "le-chameau-ivre-14.webp",
            "le-chameau-ivre-15.webp",
            "le-chameau-ivre-16.webp",
            "le-chameau-ivre-17.webp",
            "le-chameau-ivre-18.webp",
            "le-chameau-ivre-19.webp",
            "le-chameau-ivre-2.webp",
            "le-chameau-ivre-20.webp",
            "le-chameau-ivre-21.webp",
            "le-chameau-ivre-22.webp",
            "le-chameau-ivre-23.webp",
            "le-chameau-ivre-24.webp",
            "le-chameau-ivre-25.webp",
            "le-chameau-ivre-26.webp",
            "le-chameau-ivre-27.webp",
            "le-chameau-ivre-28.webp",
            "le-chameau-ivre-29.webp",
            "le-chameau-ivre-3.webp",
            "le-chameau-ivre-30.webp",
            "le-chameau-ivre-4.webp",
            "le-chameau-ivre-5.webp",
            "le-chameau-ivre-6.webp",
            "le-chameau-ivre-7.webp",
            "le-chameau-ivre-8.webp",
            "le-chameau-ivre-9.webp"
        ]
    }
};
window.PROJECTS_DATA = PROJECTS_DATA;
