const PROJECTS_DATA = {
    "appartement-st-saens": {
        "title": "Appartement St Saëns",
        "category": "Particulier",
        "location": "Béziers",
        "description": "Aménagement de l'Appartement St Saëns au cœur de Béziers.",
        "folder": "assets/images/realisations/particuliers/07-appartement-st-saens",
        "hero": "appartement-st-saens-beziers-architecte-interieur-1.webp",
        "thumbnail": "appartement-st-saens-beziers-architecte-interieur-2.webp",
        "images": [
            "appartement-st-saens-beziers-architecte-interieur-1.webp",
            "appartement-st-saens-beziers-architecte-interieur-2.webp",
            "appartement-st-saens-beziers-architecte-interieur-3.webp",
            "appartement-st-saens-beziers-architecte-interieur-4.webp",
            "appartement-st-saens-beziers-architecte-interieur-5.webp"
        ]
    },
    "vrac": {
        "title": "Vrac",
        "category": "Mixte",
        "location": "Divers",
        "description": "Un petit pêle-mêle de nos projets, nos inspirations et tout ce qu'on aime.",
        "folder": "assets/images/realisations/Vrac",
        "hero": "IMG_4356.webp",
        "thumbnail": "IMG_7803.webp",
        "images": [
            "2668AD4C-A97D-40BC-BDF4-2E3020BB35D4.webp",
            "8551c524-8aa4-4e2c-a776-770a337c1b35.webp",
            "d0cedf01-b565-4994-8881-54d82f47c2c0.webp",
            "IMG_0280.webp",
            "IMG_0283.webp",
            "IMG_0284.webp",
            "IMG_0344.webp",
            "IMG_0847.webp",
            "IMG_0914.webp",
            "IMG_1268.webp",
            "IMG_1269.webp",
            "IMG_1391.webp",
            "IMG_1394.webp",
            "IMG_1395.webp",
            "IMG_1482.webp",
            "IMG_1534.webp",
            "IMG_1982.webp",
            "IMG_2062.webp",
            "IMG_2066.webp",
            "IMG_2068.webp",
            "IMG_2210.webp",
            "IMG_2218.webp",
            "IMG_2220.webp",
            "IMG_2222.webp",
            "IMG_2224.webp",
            "IMG_2225.webp",
            "IMG_2227.webp",
            "IMG_2228.webp",
            "IMG_2581.webp",
            "IMG_2630.webp",
            "IMG_2631.webp",
            "IMG_2639.webp",
            "IMG_2640.webp",
            "IMG_2733.webp",
            "IMG_2805.webp",
            "IMG_2829.webp",
            "IMG_4182.webp",
            "IMG_4184.webp",
            "IMG_4185.webp",
            "IMG_4337.webp",
            "IMG_4341.webp",
            "IMG_4343.webp",
            "IMG_4349.webp",
            "IMG_4356.webp",
            "IMG_4373.webp",
            "IMG_4382.webp",
            "IMG_4491.webp",
            "IMG_4686.webp",
            "IMG_4690.webp",
            "IMG_4701.webp",
            "IMG_5017.webp",
            "IMG_5345.webp",
            "IMG_5352.webp",
            "IMG_6075.webp",
            "IMG_6472.webp",
            "IMG_7100.webp",
            "IMG_7109.webp",
            "IMG_7110.webp",
            "IMG_7118.webp",
            "IMG_7566.webp",
            "IMG_7798.webp",
            "IMG_7803.webp",
            "IMG_8688.webp",
            "IMG_8794.webp",
            "IMG_8801.webp",
            "IMG_8803.webp",
            "IMG_8804.webp",
            "IMG_8850.webp",
            "IMG_8938.webp",
            "IMG_8993.webp",
            "IMG_8994.webp",
            "IMG_8996.webp",
            "IMG_8998.webp",
            "IMG_8999.webp",
            "IMG_9006.webp",
            "IMG_9843.webp",
            "IMG_9936.webp"
        ]
    },
    "maison-dagde": {
        "title": "La Maison d'Agde",
        "category": "Particulier",
        "location": "Agde",
        "description": "Une rénovation contemporaine alliant épure et confort dans le centre historique.",
        "folder": "assets/images/realisations/particuliers/01-maison-dagde",
        "hero": "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "images": [
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "maison-dagde-mobilier-design-luxueux-beziers-architecte-interieur-4.webp"
        ]
    },
    "maison-cersoise": {
        "title": "Maison Cersoise",
        "category": "Particulier",
        "location": "Cers",
        "description": "L'élégance du design italien au cœur d'une villa méditerranéenne.",
        "folder": "assets/images/realisations/particuliers/02-maison-cersoise",
        "hero": "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
        "images": [
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-cersoise-mobilier-design-luxueux-beziers-architecte-interieur-3.webp"
        ]
    },
    "maison-coloree": {
        "title": "La Maison Colorée",
        "category": "Particulier",
        "location": "Béziers",
        "description": "Un jeu audacieux de textures et de couleurs pour un intérieur vibrant.",
        "folder": "assets/images/realisations/particuliers/03-maison-coloree",
        "hero": "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "thumbnail": "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
        "images": [
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "maison-coloree-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "appartement-nimes": {
        "title": "Appartement Nîmes",
        "category": "Particulier",
        "location": "Nîmes",
        "description": "Minimalisme et lumière pour cet appartement de ville aux lignes pures.",
        "folder": "assets/images/realisations/particuliers/04-appartement-nimes",
        "hero": "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
        "thumbnail": "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "images": [
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "appartement-nimes-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "lago-cap-dagde": {
        "title": "Lago Welcome Cap d'Agde",
        "category": "Particulier",
        "location": "Cap d'Agde",
        "description": "L'univers suspendu de Lago pour une expérience de vie unique face à la mer.",
        "folder": "assets/images/realisations/particuliers/05-lago-cap-dagde",
        "hero": "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
        "thumbnail": "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
        "images": [
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-1.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-2.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-3.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-4.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-5.webp",
            "lago-cap-dagde-mobilier-design-luxueux-beziers-architecte-interieur-6.webp"
        ]
    },
    "maison-st-clement": {
        "title": "Maison St Clément",
        "category": "Particulier",
        "location": "St Clément de Rivière",
        "description": "Aménagement et décoration d'une maison de caractère pour un intérieur élégant et intemporel.",
        "folder": "assets/images/realisations/particuliers/06-maison-st-clement",
        "hero": "maison-st-clement-mobilier-design-beziers-1.webp",
        "thumbnail": "maison-st-clement-mobilier-design-beziers-6.webp",
        "images": [
            "maison-st-clement-mobilier-design-beziers-1.webp",
            "maison-st-clement-mobilier-design-beziers-2.webp",
            "maison-st-clement-mobilier-design-beziers-3.webp",
            "maison-st-clement-mobilier-design-beziers-4.webp",
            "maison-st-clement-mobilier-design-beziers-5.webp",
            "maison-st-clement-mobilier-design-beziers-6.webp",
            "maison-st-clement-mobilier-design-beziers-7.webp",
            "maison-st-clement-mobilier-design-beziers-8.webp",
            "maison-st-clement-mobilier-design-beziers-9.webp",
            "maison-st-clement-mobilier-design-beziers-10.webp"
        ]
    },
    "technilum": {
        "title": "Technilum",
        "category": "Professionnel",
        "location": "Maureilhan",
        "description": "Aménagement d'espaces de travail innovants alliant ergonomie et esthétique industrielle.",
        "folder": "assets/images/realisations/professionnels/01-technilum",
        "hero": "technilum-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://www.technilum.com/",
        "images": [
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-10.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-11.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-8.webp",
            "technilum-mobilier-bureau-design-beziers-architecte-interieur-9.webp"
        ]
    },
    "cassina-villa-guy": {
        "title": "Cassina à la Villa Guy",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Une rencontre prestigieuse entre le mobilier Cassina et le cadre historique de la Villa Guy.",
        "folder": "assets/images/realisations/professionnels/02-cassina-villa-guy",
        "hero": "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
        "thumbnail": "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "images": [
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-10.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-11.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-12.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-8.webp",
            "cassina-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-9.webp"
        ]
    },
    "mediatheque-beziers": {
        "title": "Médiathèque Béziers",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Un espace public repensé pour le confort, la lecture et l'échange culturel.",
        "folder": "assets/images/realisations/professionnels/03-mediatheque-beziers",
        "hero": "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
        "thumbnail": "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
        "website": "http://www.mediatheque-beziers-agglo.org",
        "images": [
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "mediatheque-beziers-mobilier-bureau-design-beziers-architecte-interieur-4.webp"
        ]
    },
    "projet-photo": {
        "title": "Projet Photo",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Mise en scène artistique de mobiliers iconiques dans un cadre architectural singulier.",
        "folder": "assets/images/realisations/professionnels/04-projet-photo",
        "hero": "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "images": [
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "projet-photo-mobilier-bureau-design-beziers-architecte-interieur-7.webp"
        ]
    },
    "hotel-la-prison": {
        "title": "Hôtel La Prison",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Une métamorphose audacieuse où l'histoire rencontre le luxe contemporain.",
        "folder": "assets/images/realisations/professionnels/05-hotel-la-prison",
        "hero": "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "thumbnail": "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
        "website": "https://www.hotellaprison.com/",
        "images": [
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "hotel-la-prison-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "hotel-particulier": {
        "title": "Hôtel Particulier",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Restauration d'un lieu d'exception avec une sélection de pièces de design intemporelles.",
        "folder": "assets/images/realisations/professionnels/06-hotel-particulier",
        "hero": "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://hotelparticulierbeziers.com",
        "images": [
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "hotel-particulier-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "appartement-lago-villa-guy": {
        "title": "Appartement Lago Villa Guy",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "L'élégance du mobilier italien dans un écrin biterrois historique.",
        "folder": "assets/images/realisations/professionnels/07-appartement-lago-villa-guy",
        "hero": "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
        "website": "https://www.lavillaguy.com",
        "images": [
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "appartement-lago-villa-guy-mobilier-bureau-design-beziers-architecte-interieur-6.webp"
        ]
    },
    "souki-lodge": {
        "title": "Souki Lodge",
        "category": "Professionnel",
        "location": "Cabrières",
        "description": "Une immersion sensorielle au design organique, suspendue entre ciel et terre.",
        "folder": "assets/images/realisations/professionnels/08-souki-lodge",
        "hero": "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
        "website": "https://www.soukilodgesandspa.com/",
        "images": [
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-1.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-2.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-3.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-4.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-5.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-6.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-7.webp",
            "souki-lodge-mobilier-bureau-design-beziers-architecte-interieur-8.webp"
        ]
    },
    "grand-hotel-du-golfe": {
        "title": "Grand Hôtel du Golfe",
        "category": "Professionnel",
        "location": "Argelès-sur-Mer",
        "description": "Mobilier contemporain et scénographie d'exception pour cet établissement historique de la Côte Vermeille, où le design dialogue avec la mer.",
        "folder": "assets/images/realisations/professionnels/09-grand-hotel-du-golfe",
        "hero": "grand-hotel-du-golfe-mobilier-design-beziers-4.webp",
        "thumbnail": "grand-hotel-du-golfe-mobilier-design-beziers-2.webp",
        "website": "https://www.grandhoteldugolfe.com/",
        "images": [
            "grand-hotel-du-golfe-mobilier-design-beziers-1.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-2.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-3.webp",
            "grand-hotel-du-golfe-mobilier-design-beziers-4.webp"
        ]
    },
    "arlett-cafe": {
        "title": "Arlett Café",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Arlett Café.",
        "folder": "assets/images/realisations/professionnels/10-arlett-cafe",
        "hero": "amenagement-arlett-cafe-beziers-8.webp",
        "thumbnail": "amenagement-arlett-cafe-beziers-8.webp",
        "images": [
            "amenagement-arlett-cafe-beziers-1.webp",
            "amenagement-arlett-cafe-beziers-2.webp",
            "amenagement-arlett-cafe-beziers-3.webp",
            "amenagement-arlett-cafe-beziers-4.webp",
            "amenagement-arlett-cafe-beziers-5.webp",
            "amenagement-arlett-cafe-beziers-6.webp",
            "amenagement-arlett-cafe-beziers-7.webp",
            "amenagement-arlett-cafe-beziers-8.webp",
            "amenagement-arlett-cafe-beziers-9.webp",
            "amenagement-arlett-cafe-beziers-10.webp",
            "amenagement-arlett-cafe-beziers-11.webp",
            "amenagement-arlett-cafe-beziers-12.webp",
            "amenagement-arlett-cafe-beziers-13.webp"
        ]
    },
    "bureaux": {
        "title": "Bureaux",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Bureaux.",
        "folder": "assets/images/realisations/professionnels/11-bureaux",
        "hero": "amenagement-bureaux-professionnels-beziers-2.webp",
        "thumbnail": "amenagement-bureaux-professionnels-beziers-2.webp",
        "images": [
            "amenagement-bureaux-professionnels-beziers-1.webp",
            "amenagement-bureaux-professionnels-beziers-2.webp",
            "amenagement-bureaux-professionnels-beziers-3.webp",
            "amenagement-bureaux-professionnels-beziers-4.webp",
            "amenagement-bureaux-professionnels-beziers-5.webp",
            "amenagement-bureaux-professionnels-beziers-6.webp",
            "amenagement-bureaux-professionnels-beziers-7.webp",
            "amenagement-bureaux-professionnels-beziers-8.webp",
            "amenagement-bureaux-professionnels-beziers-9.webp",
            "amenagement-bureaux-professionnels-beziers-10.webp",
            "amenagement-bureaux-professionnels-beziers-11.webp",
            "amenagement-bureaux-professionnels-beziers-12.webp",
            "amenagement-bureaux-professionnels-beziers-13.webp",
            "amenagement-bureaux-professionnels-beziers-14.webp"
        ]
    },
    "halles": {
        "title": "Les Halles",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Les Halles.",
        "folder": "assets/images/realisations/professionnels/12-halles",
        "hero": "amenagement-les-halles-beziers-1.webp",
        "thumbnail": "amenagement-les-halles-beziers-1.webp",
        "images": [
            "amenagement-les-halles-beziers-1.webp",
            "amenagement-les-halles-beziers-2.webp",
            "amenagement-les-halles-beziers-3.webp",
            "amenagement-les-halles-beziers-4.webp",
            "amenagement-les-halles-beziers-5.webp",
            "amenagement-les-halles-beziers-6.webp",
            "amenagement-les-halles-beziers-7.webp",
            "amenagement-les-halles-beziers-8.webp",
            "amenagement-les-halles-beziers-9.webp",
            "amenagement-les-halles-beziers-10.webp",
            "amenagement-les-halles-beziers-11.webp",
            "amenagement-les-halles-beziers-12.webp",
            "amenagement-les-halles-beziers-13.webp"
        ]
    },
    "imprimerie-combes-hund": {
        "title": "Imprimerie Combes Hund",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Imprimerie Combes Hund.",
        "folder": "assets/images/realisations/professionnels/13-imprimerie-combes-hund",
        "hero": "amenagement-imprimerie-combes-hund-beziers-2.webp",
        "thumbnail": "amenagement-imprimerie-combes-hund-beziers-2.webp",
        "images": [
            "amenagement-imprimerie-combes-hund-beziers-1.webp",
            "amenagement-imprimerie-combes-hund-beziers-2.webp",
            "amenagement-imprimerie-combes-hund-beziers-3.webp",
            "amenagement-imprimerie-combes-hund-beziers-4.webp"
        ]
    },
    "le-bistrot-cersois": {
        "title": "Le Bistrot Cersois",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Le Bistrot Cersois.",
        "folder": "assets/images/realisations/professionnels/14-le-bistrot-cersois",
        "hero": "amenagement-le-bistrot-cersois-1.webp",
        "thumbnail": "amenagement-le-bistrot-cersois-1.webp",
        "images": [
            "amenagement-le-bistrot-cersois-1.webp",
            "amenagement-le-bistrot-cersois-2.webp",
            "amenagement-le-bistrot-cersois-3.webp",
            "amenagement-le-bistrot-cersois-4.webp",
            "amenagement-le-bistrot-cersois-5.webp",
            "amenagement-le-bistrot-cersois-6.webp",
            "amenagement-le-bistrot-cersois-7.webp",
            "amenagement-le-bistrot-cersois-8.webp"
        ]
    },
    "le-chameau-ivre": {
        "title": "Le Chameau Ivre",
        "category": "Professionnel",
        "location": "Béziers",
        "description": "Aménagement professionnel - Le Chameau Ivre.",
        "folder": "assets/images/realisations/professionnels/15-le-chameau-ivre",
        "hero": "amenagement-le-chameau-ivre-beziers-1.webp",
        "thumbnail": "amenagement-le-chameau-ivre-beziers-1.webp",
        "images": [
            "amenagement-le-chameau-ivre-beziers-1.webp",
            "amenagement-le-chameau-ivre-beziers-2.webp",
            "amenagement-le-chameau-ivre-beziers-3.webp",
            "amenagement-le-chameau-ivre-beziers-4.webp",
            "amenagement-le-chameau-ivre-beziers-5.webp",
            "amenagement-le-chameau-ivre-beziers-6.webp",
            "amenagement-le-chameau-ivre-beziers-7.webp",
            "amenagement-le-chameau-ivre-beziers-8.webp",
            "amenagement-le-chameau-ivre-beziers-9.webp",
            "amenagement-le-chameau-ivre-beziers-10.webp",
            "amenagement-le-chameau-ivre-beziers-11.webp"
        ]
    }
};

window.PROJECTS_DATA = PROJECTS_DATA;
